
const grid=document.getElementById("recipes"),search=document.getElementById("search"),categoriesEl=document.getElementById("categories"),countEl=document.getElementById("count"),dialog=document.getElementById("dialog"),modal=document.getElementById("modal");
let activeCategory="Todas", currentRecipe=null;const categories=["Todas",...Array.from(new Set(recipes.map(r=>r.category)))];
function renderCategories(){categoriesEl.innerHTML="";categories.forEach(cat=>{const b=document.createElement("button");b.className="chip"+(cat===activeCategory?" active":"");b.textContent=cat;b.addEventListener("click",()=>{activeCategory=cat;renderCategories();renderRecipes()});categoriesEl.appendChild(b)})}
function textForSearch(r){return[r.title,r.category,r.time,r.servings,r.difficulty,r.tags.join(" "),r.ingredients.join(" "),r.steps.join(" "),r.tip].join(" ").toLowerCase()}
function renderRecipes(){const q=search.value.trim().toLowerCase();const filtered=recipes.filter(r=>activeCategory==="Todas"||r.category===activeCategory).filter(r=>textForSearch(r).includes(q));countEl.textContent=filtered.length;grid.innerHTML="";if(!filtered.length){grid.innerHTML='<div class="empty">No he encontrado recetas con esa búsqueda.</div>';return}filtered.forEach(r=>{const card=document.createElement("article");card.className="card";card.innerHTML=`<h2>${r.title}</h2><div class="meta">${r.category} · ${r.time} · ${r.servings} · ${r.difficulty}</div><div class="tags">${r.tags.map(t=>`<span class="tag">${t}</span>`).join("")}</div>`;card.addEventListener("click",()=>openRecipe(r));grid.appendChild(card)})}
function openRecipe(r){currentRecipe=r;modal.innerHTML=`<button class="close" onclick="dialog.close()" aria-label="Cerrar">×</button><h2>${r.title}</h2><div class="meta">${r.category}</div><div class="info"><div><strong>Tiempo</strong>${r.time}</div><div><strong>Raciones</strong>${r.servings}</div><div><strong>Dificultad</strong>${r.difficulty}</div><div><strong>Categoría</strong>${r.category}</div></div><h3>Ingredientes</h3><ul>${r.ingredients.map(i=>`<li>${i}</li>`).join("")}</ul><h3>Preparación</h3><ol>${r.steps.map(s=>`<li>${s}</li>`).join("")}</ol><h3>Consejo</h3><p>${r.tip}</p><button class="print-button" type="button" onclick="printRecipe()">🖨️ Imprimir receta</button>`;dialog.showModal()}
function printRecipe(){if(!currentRecipe)return;const r=currentRecipe;const w=window.open("","_blank","width=800,height=700");if(!w){alert("El navegador ha bloqueado la ventana de impresión. Permite las ventanas emergentes e inténtalo de nuevo.");return}w.document.write(`<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><title>${r.title}</title><style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif;color:#222;max-width:760px;margin:32px auto;padding:0 24px;line-height:1.45}h1{font-size:30px;margin-bottom:6px}h2{font-size:20px;margin-top:26px;border-bottom:1px solid #ccc;padding-bottom:5px}.meta{color:#555;margin-bottom:20px}.info{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:18px 0}.info div{border:1px solid #ddd;border-radius:10px;padding:9px;font-size:13px}.info strong{display:block}li{margin:7px 0}.tip{background:#f4f4f4;border-radius:10px;padding:12px}@media print{body{margin:0;max-width:none}.info div{break-inside:avoid}}</style></head><body><h1>${r.title}</h1><div class="meta">Recetario de Emilio · ${r.category}</div><div class="info"><div><strong>Tiempo</strong>${r.time}</div><div><strong>Raciones</strong>${r.servings}</div><div><strong>Dificultad</strong>${r.difficulty}</div><div><strong>Categoría</strong>${r.category}</div></div><h2>Ingredientes</h2><ul>${r.ingredients.map(i=>`<li>${i}</li>`).join("")}</ul><h2>Preparación</h2><ol>${r.steps.map(s=>`<li>${s}</li>`).join("")}</ol><h2>Consejo</h2><p class="tip">${r.tip}</p></body></html>`);w.document.close();w.focus();setTimeout(()=>{w.print();w.close()},250)}
search.addEventListener("input",renderRecipes);renderCategories();renderRecipes();
